server:
  port: 8081

kafka:
  bootstrapServers: 127.0.0.1:49816
  consumers:
    group: task-group
    topicName: task_topic
    replyTopic: reply_topic

#Base de datos.
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=skttask;integratedSecurity=false;encrypt=false;trustServerCertificate=true
    username: sa
    password: sqlPassword!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#flyway:
#  locations: classpath:db/migration