package com.skytouch.task.commons.dtos.responses;

import lombok.Data;

/**
 * DTO to store error messages generated by failed request validations in rest controllers.
 *
 * @author Waldo Terry
 */
@Data
public class RequestValidationErrorResponse {
    private String field;
    private String error;
}
